# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae6f390387d3c9d67cb56a2d73b797ffcdc038c36160c92c838c7c9b24f2caca113c9cce7c458033f0c147891117a7ea4a8cc087ca74f62e66a31cbfc8bdd79f

test:
  secret_key_base: 5669fd38107342a6595bcc12826987ee8f5fd0fbf81886760c479b307827a8ca40553bdb23cef4243cb6eb4d79fb5036ebbc08e5c427e8bdf8661cfdd7f668db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
